### ISSUE TITLE
Network error in Library Browser

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1828] opened 2022-11-17 20:38 UTC
In 2.17, if I

1. visit the Library Browser
2. select "Calculus - single variable" from the dropdown Subject menu
3. click View Problems _quickly, before `There are ____ matching WeBWorK problems` has time to update_

Then Firefox throws an error at me in some kind of dialog box:
`/webwork2/instructorXMLHandler  NetworkError when attempting to fetch resource.`

Is this something that can be fixed? Or sidestepping the issue, is it possible something about my configuration could be improved to speed up the time to update the count of matching exercises?

**Comment by somiaj** [comment] 2022-11-17 20:59
I double checked that I do get the same issue (though I have to be really quick). It appears that when you click view it sends a request to load a new page, thus interrupting the XLMhandler, and even though the error appears, the page still loads and renders the problems just fine.

How long is it taking your system to fetch the problems? Here it is less than a second.

**Comment by Alex-Jordan** [comment] 2022-11-17 21:07
I wasn't trying to be fast when I stumbled upon this. I was just trying to check that Library Browser worked on a new installation. And it was consistently happening until I had developer tools open. Having that open slowed me down enough for clicking the show button, and then for a bit I was confused as to why the problem went away "just because developer tools were open". Eventually I realized it had to do with the fetching of the updated count.

Anyway, it's between 1 and 2 seconds for me.

**Comment by drgrice1** [comment] 2022-11-17 21:49
I was able to reproduce this once, the first time I tried it.  Then I couldn't do it again.  Lost my click speed I guess.  I could only reproduce it on my production server with WeBWorK 2.17, and not on the develop branch with morbo.  That is probably only because there is no way I could possibly beat the network response to and from the local morbo server though.

In any case, the one time I reproduced it, I sat there looking at the toast reporting the error, and it suddenly disappeared and the page loaded the problems anyway.

What is happening is that when "View Problems" button is clicked it submits the form on the page.  Any time a new page request is submitted it aborts any javascript requests in progress that have not yet completed.   Unfortunately, I don't think there is anything that we can do about that.  I doubt there is really anything you could do with your configuration to speed things up either.  It is simply a factor of the speed of the connection between the computer and the server, and the time it takes for the server to process the request.

**Comment by pstaabp** [comment] 2023-01-04 20:51
This was fixed in #1829.

**Closed by pstaabp** 2023-01-04 20:51 UTC
