### ISSUE TITLE
Grade Test button missing in gateway quizzes

### ISSUE THREAD

**Issue by awmorp** [openwebwork/webwork2#1822] opened 2022-10-24 12:40 UTC
I run a gateway quiz in a subject with ~1000 students with Webwork v2.16. This semester I had 4 students who did not have a Grade Test button at the bottom of their quiz. Here is a screenshot:

![image](https://user-images.githubusercontent.com/8839416/197528775-3b5c6042-ac4f-419a-92c9-743c4af55b11.png)

Any idea what could cause this?

**Comment by drgrice1** [comment] 2023-04-29 14:33
I have never seen this occur, and have no clue how this could happen and can not reproduce it.  I suspect that you either have local modifications on your server that are causing issues, or that you have some javascript acting on the page that is not part of webwork that is causing the problem.  Check your console to see if there are any warnings or errors.

**Comment by drgrice1** [comment] 2023-05-27 21:31
I am closing this issue.  I am not able to reproduce this issue, and there has been no follow up from the original author of this issue.

**Closed by drgrice1** 2023-05-27 21:31 UTC

**Comment by awmorp** [comment] 2023-05-29 01:21
Apologies for not responding sooner. We don't have any local modifications or custom javascript that I'm aware of. I suspected it could be the student's browser or internet connection to blame. Anyhow we have switched to running the quiz assessments in a controlled computer lab now so browser and internet issues should be less of a problem. Ok with me to close the issue.
