### ISSUE TITLE
Test is completed but not submitted.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#2041] opened 2023-06-08 16:58 UTC
Just had a student complete a test, but the grade test submit only partially worked.  I can see their grade as if it were graded, but it isn't considered submitted. Here are some screenshots.

First the test launch screen:

![issue-test1](https://github.com/openwebwork/webwork2/assets/18082412/8354c0da-f18e-4635-8c2e-85f581e01699)

Test page

![issue-test2](https://github.com/openwebwork/webwork2/assets/18082412/8c052668-1b93-47c6-b161-fc20131e87ac)

Student Progress Page

![issue-test3](https://github.com/openwebwork/webwork2/assets/18082412/108470b0-2b39-4bb4-8c28-5dc6bf138817)

As shown, the test was graded and has a score (and the test only allowed a single submit).  The student was not able to get back into to the test (I had them check), since it was graded, but yet the test still isn't considered 'submitted'.

edit: Added labels to the screenshots.

**Comment by somiaj** [comment] 2023-06-08 17:12
Just to add some more info, this student's laptop cannot connect to the universitie's wifi for some reason, so instead they sit in the corner of the room near the window which they have 1 bar of phone service, and use their phone as a hot spot.  So could it be some lag in the grade test submit making it so the test doesn't fully finish being graded?

**Comment by drgrice1** [comment] 2023-06-14 17:42
This may be some odd issue with internet connectivity and some database write that was terminated prematurely.  If you can reliably reproduce this, then we have something to work with.  Otherwise, it is unlikely that anything can be done about this.  However, even if this can be reproduced reliably, there may not be anything that can be done.  Most likely we would need to implement transactions that can cancelled and rolled back when errors occur to fix this type of thing.

You might look closely at the database and see if there is anything odd for this student and set.

**Comment by somiaj** [comment] 2023-06-14 19:19
It appears that the column `version_last_attempt_time` from the versioned `CourseID_set_user` table never got filled in (it is zero).  Since this time never got recorded, the test is considered not completed.  Appears that all of the grade data from the problems was recorded, which is why there was a grade.  Looking at the `CourseID_problem_user` table for this test, I see that all the problems were correctly flagged as `attempted`.  So seems we might need to double check what would cause `version_last_attempt_time` from being recorded.

**Comment by Alex-Jordan** [comment] 2023-07-24 15:43
Are you able to see if the student has nonzero scores up to a point, but then starting with some problem it's all zero scores? I'm wondering if there are more similarities to #2148 and if something about certain problems can be in play.

**Comment by drgrice1** [comment] 2023-07-24 15:49
I suspect the two are quite closely tied together then.  I suspect that there is a problem that uses the LaTeXImage.pm module, and there is an error occurring in the latex for that problem (possibly dependent on seed).  Then the issue is that `--interaction=nonstopmode` needs to be added to the `latex` (or `pdflatex`) calls in LaTeXImage.pm.  When an error occurs currently, latex stops and waits for input, and causes the request to hang.  Then you have to wait for the PG timeout to happen.

**Comment by Alex-Jordan** [comment] 2023-07-24 15:52
Is that consistent with how I can still load the problem and see its image, even with the seed that was used? (But only when I load it in certain ways.)

**Comment by drgrice1** [comment] 2023-07-24 16:47
I am not certain what is happening that is making it so that with a fixed seed you can view it when loaded in some ways, but not with others.

**Comment by pstaabp** [comment] 2024-02-21 14:39
Fixed in #2154

**Closed by pstaabp** 2024-02-21 14:39 UTC
