### ISSUE TITLE
machine rounding error with conditional release

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1530] opened 2021-12-20 23:43 UTC
A machine rounding error has popped up, and I'm unsure what is the best way to address it.  An instructor had conditional release set to 80%. Meaning if a student has reached at least 80% on set A, they get access to start set B. For this instructor, set A has 5 exercises. Students who get 4 correct should reach 80% and gain access to set B. But they are not getting access.

I think that the score 4/5 is becoming 0.79995422... due to machine rounding error. And then that does not pass the test (because it is less than 0.8).

The comparison happens at line 1232 of lib/WeBWorK/Utils.pm. Instead of comparing `$r_score < $restriction`, it could become `$r_score + 0.001 < $restriction` or something like that. That should work in practice, but it feels like a hack to work around the machine rounding error. Can anyone imagine a better solution?

**Comment by dlglin** [comment] 2021-12-21 16:23
I don't see a better way to handle this than to add a fudge factor as you suggest.

**Comment by drgrice1** [comment] 2021-12-21 21:37
Is your 5 exercise example hypothetical, or is that what the instructor actually has?

I just tested this by creating a homework set with 5 problems, and then making another homework set conditional on that one with the 80% access requirement.  The result was successful.  After working four of the five in the first homework set correctly, the restricted set was opened.  Checking, the `$r_score` and `$restriction` values in the `sub is_restricted` method of `lib/WeBWorK/Utils.pm` on line 1232, I see that both are exactly 0.8 with no rounding.

Is there something else going on that is causing the rounding in your situation?  I left the question weights all at 1 in my first test.  Then tried again with all weights set to 2.  Both worked, but perhaps the instructor in your situation used different equal weights?  Or is this perhaps the problem?  I.e., the weights are not all the same, and so four questions may not be 80%?

**Comment by Alex-Jordan** [comment] 2021-12-21 23:21
It's not hypothetical, but it may have been an 8/10 situation. This was a few months back, and she indicated that changing the setting to 70% was not a good solution. That may indicate that it was indeed 8/10, not 4/5. I added a 75% option for her and that met her needs. I'll see if I can track down if it was really a 10-question set.

**Comment by Alex-Jordan** [comment] 2021-12-21 23:30
I looked at this instructors quizzes. The first one has a release condition for five sets: "L03,L04,L05,L06,L07". Those sets have problem counts: 5, 6, 7, 10, 5. There is no weighting in those sets (each problem uses weight 1).

I'll ask the instructor for permission to mess around in her course and try to reproduce it.

**Comment by drgrice1** [comment] 2021-12-21 23:34
Sounds good.

I think that rather than adding 0.001 to the score, it would be better just to round the score to two decimal places before comparing.

**Comment by Alex-Jordan** [comment] 2021-12-31 06:31
I just confirmed the issue on the develop branch, although it's not happening like I thought it was.

I made a set with 10 exercises and made another set be conditional on getting 80% for the first set. I assigned it to a student. Then logged in as that student and answered the first 8 questions correctly.  I am still not given access to the second set.

I had the score and the restriction print out to the apache log, and the score was fine: 0.8.  But the restriction was actually the problem: 0.800000011920929.

I'm opening a PR where both things get rounded.

**Comment by drgrice1** [comment] 2021-12-31 17:47
So I tried to do the same that you did, and created a set with 10 problems, and made another set conditional on getting 80% on that that set.  After getting 8 of the problems on the first set correct, the second set was opened.  I also had the score and restriction print to the apache error log, and both showed as 0.8.

I think the pull request to round these values should be fine, but I am unable to reproduce the issue still.  Are you still running Ubuntu 18.04 on the server that you are testing this on?  I wonder if something has changed with perl from the version on Ubuntu 18.04 to Ubuntu 20.04 that fixes this?

**Comment by Alex-Jordan** [comment] 2021-12-31 21:47
All the instances I've encountered of this have been on 18.

**Comment by drdrew42** [comment] 2022-01-12 16:59
I am also unable to reproduce on Ubuntu 20.04 (perl 5.30)

**Comment by pstaabp** [comment] 2022-01-21 19:07
Now fixed with #1535

**Closed by pstaabp** 2022-01-21 19:07 UTC
