### ISSUE TITLE
Bug in in-problem-manual-grader: Unable to view edited problems in gateway quizzes.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1187] opened 2021-02-07 13:06 UTC
Hello,

I have recently switched to the develop branch and am using the manual-problem-grader pull request. In this version we can no longer view edited problems that are part of a gateway quiz. This worked just fine in the master branch. We can get around the issue by doing our edits in a copy of the assignment that is a normal homework problem set. Here is the error that we get if we try to view a problem that is inside a gateway quiz.

```
Error messages

    Can't locate object method "version_id" via package "WeBWorK::DB::Record::UserProblem" at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm line 422. 

Call stack

The information below can help locate the source of the problem.

    in WeBWorK::ContentGenerator::GatewayQuiz::get_instructor_comment called at line 2123 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
    in WeBWorK::ContentGenerator::GatewayQuiz::body called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm
    in WeBWorK::Template::template called at line 610 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
    in WeBWorK::ContentGenerator::content called at line 233 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
    in WeBWorK::ContentGenerator::go called at line 386 of /opt/webwork/webwork2/lib/WeBWorK.pm
```

**Comment by somiaj** [comment] 2021-02-07 14:04
It appears that the issue isn't a part of the develop branch, but in some change the in-manual-problem-grader addition, the error is coming from the new sub, `get_instructor_comment` which was added with this commit.

https://github.com/openwebwork/webwork2/pull/1162/commits/6a7185284f1a87c855cad9c93aab369f2695bdaa

**Comment by somiaj** [comment] 2021-02-07 15:58
So removing `$problem->version_id` fixes the issue for me. This is a crude fix, but what I did was take the line that I got the error from:

```perl
       my $userPastAnswerID = $db->latestProblemPastAnswer($self->{ce}{courseName}, $problem->user_id,
               $problem->set_id . ",v" . $problem->version_id, $problem->problem_id);
```

and replaced it with

```perl
        my $userPastAnswerID = $db->latestProblemPastAnswer($self->{ce}{courseName}, $problem->user_id,
                $problem->set_id, $problem->problem_id);
```

I don't know enough to do a better fix (or any unforeseen issues with not having the version id printed), but this at least isolates the issue hopefully.

**Comment by drgrice1** [comment] 2021-02-07 17:43
Can you clarify exactly what you are doing to replicate this issue?  I can't reproduce it.

**Comment by drgrice1** [comment] 2021-02-07 18:13
@somiaj:  Test this with the last commit.  That should fix it.

Removing the version id will certainly not work because that is needed to retrieve the actual past answer from the database for the version that is being viewed.

**Comment by Alex-Jordan** [comment] 2021-02-07 18:52
Would either of you mind walking through steps to take to reproduce the issue? I'd like to try it on my server and see if I should pull that latest commit. (Otherwise, I am trying to avoid new pulls until the term is over.)

**Comment by somiaj** [comment] 2021-02-07 19:06
1. Create a gateway quiz.
2. Go to the quiz configuration page so you can see all the questions.
3. Click on the 'view' icon (an eyeball) for any problem.
4. Profit -- you'll see the error.

**Comment by somiaj** [comment] 2021-02-07 19:10
@drgrice1 That commit fixed the issue. Thanks

**Comment by drgrice1** [comment] 2021-02-07 19:42
@somiaj: Yeah, I ended up being able to reproduce the issue in that way.  The problem is that when viewing the problem in that way, there isn't a valid versioned problem.  The gateway quiz module creates a fake problem that doesn't correspond to an actual database entry.  For an actual problem in a gateway quiz the problem is a versioned problem, and the version_id call works as it should.

**Comment by somiaj** [comment] 2021-02-07 19:54
https://github.com/openwebwork/webwork2/pull/1162/commits/dc6c6f8ebd1b21e2aa16630572ff2e0ece4129b6 fixes the issue.

**Comment by somiaj** [comment] 2021-04-05 01:42
Hello,

Appears this bug isn't fully fixed, as there is still an issue if you are acting as a student. When acting as a student and trying to edit a question in a gateway quiz via the method described above, the edit screen works fine. But if you try to view the question you get an error (you also get this error if you try to update a question, though the update works, the view after the update fails, so the bug is with viewing the question).

The error I get is:

```
Warning messages

    Use of uninitialized value in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm line 1252. Use of uninitialized value in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm line 1252. 

Error messages

    Can't call method "user_id" on unblessed reference at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm line 1239. 
```

**Comment by drgrice1** [comment] 2021-04-05 02:02
@somiaj:  I am unable to reproduce your issue.  Can you give more detailed steps on how to produce the error?

**Comment by somiaj** [comment] 2021-04-05 02:15
When acting as a student:

1) Go edit a gateway quiz (maybe it has to be a quiz that the student has completed -- my case here).
2) Click the edit button on a question, so the .pg editor opens up (the url is /webwork2/<Course>/instructor/pgProblemEditor2/<Quizname>/<Quizprob>/?effectiveUser=&key=&user=&make_local_copy=0 is what is in the url, I blanked the actual values of the variables).
3) Click on 'take action!' under view tab, this causes the error.

@drgrice1 that detailed enough?

**Comment by drgrice1** [comment] 2021-04-05 02:19
That doesn't work for me.  I am still unable to reproduce your error.

**Comment by somiaj** [comment] 2021-04-05 02:28
My version of webwork is slightly behind the develop branch as I don't want to update it until after the semester is over (I did apply the patch in this bug report). Maybe it is something that is an issue on my end due to that and works fine if I was up to date. Once the semester is over and I update, I'll see if I still have the issue on a fully updated install.

**Comment by drgrice1** [comment] 2021-04-05 02:30
I have tried every possible way of editing a problem from a gateway quiz that I know of (acting as a student, editing from a students version, etc), and can not reproduce this error.   I am going to close this issue for now.  If you are fully upgraded, and can then still reproduce this error, then you can reopen it.

**Closed by drgrice1** 2021-04-05 02:30 UTC

**Comment by somiaj** [comment] 2021-04-05 02:31
Did you try to view the problem from the edit screen (not just edit the problem), that is where the issue occurs?

**Comment by drgrice1** [comment] 2021-04-05 10:48
I tried everything.  I can not reproduce your issue.
