### ISSUE TITLE
SMA and image caching

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#644] opened 2015-09-30 04:27 UTC
So, this happens:

An assignment has a problem using a graph from `PGgraphmacros.pl`. The problem has not set `$refreshCachedImages` to `true`. Usually, unless something changes with the code for the problem, there is no issue with that from the student's perspective.

But if the problem allows for SMA, then the student will see the SMA version with the original version's image, while being expected to answer the new question based on a new image.

(I just got an earful about this from an understandably confused student who could not understand why their submissions to the SMA version were wrong wrong wrong, and then when they entered the exact same thing to the for-credit version that was the same problem [as far as they could see, since only the image changed], it was then marked right.)

So far I've had two ideas to address this:

1. Why is `$refreshCachedImages` just not set to `true` as the default? Is it worth the reduction in traffic? I'm tempted to add `$refreshCachedImages=1`; to `$PGgraphmacros.pl` locally for our server. Or would everyone be open to that for pg?
2. Can the SMA module somehow be told to always use fresh images, no matter the value of `$refreshCachedImages`?

**Comment by goehle** [comment] 2015-09-30 11:21
I don't think either answer is correct.  Image generation is pretty
expensive and if you set refreshCachedImages to 1 then a new image is
generated every time a student hits submit.  Thats definitely too much load
on servers if its every homework and probably still isn't appropriate for
SMA.

I think this is actually a bug.  In theory the image alias should depend on
the seed of the problem, so if the problem has a new seed (say for show me
another) then it should generate a new image.  We changed some stuff around
with alias' a little while back.  Its possible that the seed isn't properly
being used to generate the image alias (which controls if and when a new
version is created).

**Comment by goehle** [comment] 2015-09-30 16:32
I tracked this down and the issue is that the problem seed is never used in the creation of the alias/resource object for the problem.  I think a good place to add it would be here: 
https://github.com/openwebwork/pg/blob/develop/lib/PGalias.pm#L113

Mike, you worked on this last, does that seem reasonable?

**Comment by goehle** [comment] 2015-10-01 12:43
Fixed in pg pull 244

**Closed by goehle** 2015-10-01 12:43 UTC
