### ISSUE TITLE
database error involving achievements

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1188] opened 2021-02-07 18:05 UTC
The problem involved is local:  set01/set01.prob12.ch04.05.CurveSketching.pg 
( originally  /Library/ASU-topics/setSecondDerivative/5-2-53.pg, modified by Paul Pearson)

Answering the first two questions when achievements is activated causes the errors below. 
MathQuill was being used, but turning it off did not solve the problem.
Turning achievements off (even with MathQuill on) did solve the problem. 

The webwork2 version is develop and has the utf8mb4 changes included. 

At the moment I don't know what the length settings on the database records for this particular class (mth142 at U of Rochester ) are.  There maybe some legacy effects since this class was created from an archived class from some years ago and these database tables were not individually updated. 

The detailed error message is:

DBD::mysql::st execute failed: Data too long for column 'frozen_hash' at row 1 at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 860.
Call stack
The information below can help locate the source of the problem.

in WeBWorK::DB::Schema::NewSQL::Std::handle_error called at line 598 of /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm
in WeBWorK::DB::Schema::NewSQL::Std::update_fields_i called at line 627 of /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm
in WeBWorK::DB::Schema::NewSQL::Std::update_records called at line 781 of /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm
in WeBWorK::DB::Schema::NewSQL::Std::put called at line 1476 of /opt/webwork/webwork2/lib/WeBWorK/DB.pm
in WeBWorK::DB::putUserAchievement called at line 327 of /opt/webwork/webwork2/lib/WeBWorK/AchievementEvaluator.pm
in WeBWorK::AchievementEvaluator::checkForAchievements called at line 2033 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::output_achievement_message called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm

PG contents:

[set01.prob11.ch04.05.CurveSketching.pg.txt](https://github.com/openwebwork/webwork2/files/5939667/set01.prob11.ch04.05.CurveSketching.pg.txt)

**Comment by drgrice1** [comment] 2021-02-07 21:02
This seems to be caused by the still_not_right.at achievement.  That achievement stores the problems set_id, problem_id, and last_answer in $localData, and that is then stored in the frozen_hash column of the achievement_user table.  That column has type VARCHAR(1024).

This problem has many answers, and all of those answers and the MathQuill latex versions of those answers (if enable) are then stored in that column.   The last_answer value for this problem easily becomes quite long. This seems to be exceeding the size limit of the VARCHAR(1024) type.  I was able to replicate this on the develop branch.

**Comment by drgrice1** [comment] 2021-02-07 23:25
Here is a fix for removing the MathQuill latex versions of the answer from the data that is stored by the still_not_right.at achievement.  Add the lines
```perl
$last_answer = $problem->last_answer;
$last_answer =~ s/"MaThQuIlL_[^"]*","[^"]*",//g;
```
at the beginning of that file, and then change all occurrences of $problem->last_answer below to $last_answer.  This fixes the problem for me.

Although this does not fix the general problem that is occurring, and that is illuminated here.  That is that an achievement evaluator could somewhat easily store enough data to exceed the size limitations of the VARCHAR(1024) database type.  It seems that it would be a good idea to switch to another database type that can hold more data.

**Comment by drgrice1** [comment] 2024-01-17 12:28
I am closing this as it has been fixed (by using a database type that holds more data).

**Closed by drgrice1** 2024-01-17 12:28 UTC
