### ISSUE TITLE
restricted editing of course.conf

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1454] opened 2021-07-18 22:06 UTC
There are reasons to disallow a professor-level user from editing a course.conf file. For this, we have https://github.com/openwebwork/webwork2/blob/48b9feadd8054259c0c25ca8758e0926915e0fec/conf/defaults.config#L503

But this is easy to get around. A professor still has the ability to rename files. For example, while logged in as a professor without access to editing `course.conf`, I was able to rename `course.conf` to `course1.conf` and rename a different file as `course.conf`.

I haven't tried, but perhaps you can upload a new `course.conf` file and it would overwrite the one that is there. Or even if that is prevented, my guess is you can put a new `course.conf` inside a `tgz` and upload that, and it would unpack and overwrite the original.

What solutions could we have for this issue?

**Comment by drgrice1** [comment] 2021-07-18 22:09
Yes, you can simply download the course.conf file, edit it, and upload it again overwriting the original. I pointed this out a long time ago. There are no protections against this at this point.

**Comment by dlglin** [comment] 2021-07-19 15:52
The attempt to protect course.conf is a hack, which is why there are ways around it.
As I see it, there were two different motivations for this:

1. To prevent instructors from accidentally locking themselves out of their courses by saving a course.conf file that either doesn't compile or has some weird change to permissions.
2. To prevent instructors from changing settings that are above their permission level.

In most cases this solves the first issue, since anyone who knows enough to rename a file or upload a tgz file is probably making deliberate changes to course.conf.  The second issue is tougher, because WW will apply any settings in course.conf, so if someone has permission to edit that file, then they can change anything about their course, including their own level of permission.

Because of this all-or-nothing nature of access to course.conf, I think that course.conf should not be editable from the UI at all.  I see a couple of ways to fix this:

1. Try and cover all of the ways of replacing that file.  So far we've identified the editor, renaming a file and uploading a tgz file, but there may be others.  The problem is that this becomes a hack on top of a hack, where we are adding a conditional in even more places.
2. Change the recommended file permissions of course.conf so that apache has read permission, but not write permission for that file.  That way we don't have to track down all of the places in the code that may overwrite that file.

**Comment by drgrice1** [comment] 2024-11-23 00:37
I am closing this.  I believe it is entirely fixed now.

**Closed by drgrice1** 2024-11-23 00:37 UTC
