### ISSUE TITLE
unproctored access to a new version of a proctored test

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2244] opened 2023-11-08 07:49 UTC
An issue was discovered while looking into #2243. A clever student taking a proctored test could gain unproctored access to a new version of a test, as described in that thread. Possible solution is to make a proctor_key be specific to one particular version of a test.

**Comment by drgrice1** [comment] 2023-11-08 21:25
I realized that this is actually much worse than I initially believed it to be.  There are other ways that this technique can be used.

One case is that the student starts the test in a proctored environment and copies the proctor username and key.  Then leaves the proctored environment and goes to another computer elsewhere, and this technique can then be used to reenter the test and continue working it.  The test can not be graded using this technique unless the test is set to require a proctor password on start only.

Another way this technique can be used is if there are multiple proctored tests in the course.  The student could start one test in a proctored environment and get the proctor username and key, and then leave and use the technique to enter and start a new version of any other proctored test in the course even while the first test has not timed out.

Making the  proctor key specific to the set and version will fix the second issue, but it won't fix the first.

**Comment by Alex-Jordan** [comment] 2023-11-08 21:57
How about making the key specific to the set, the version, and also something like the IP address? Can that ever change during a session if a computer lab has some weird setup?

**Comment by drgrice1** [comment] 2023-11-08 22:01
I had thought of that to.  That should mostly work.  The IP address can't change, but it can be spoofed.  That is certainly more challenging, and generally beyond what most hacker students attempting to cheat on a test would be capable of.

**Comment by dlglin** [comment] 2023-11-09 17:41
It is theoretically possible for the IP address to change during a session.  I can give two examples, though I can't speak to how likely they are to actually happen.

1. If a student is using a VPN (e.g. there are WW installations that require students to VPN into campus to access the WW server), then there is no guarantee that they will keep the same IP address for the whole session, particularly if they have to reconnect at some point.
2. Our NAT configuration on campus is such that when a computer with an internal IP address connects to an external site it is translated to an address from a pool of public IP addresses.  There is no guarantee that subsequent requests will use the same public address from the pool.

These types of configurations also raise another weakness of tying the key to an IP address: when using NAT it's possible that a large number of computers (possibly a whole campus) will appear to WW as if they are coming from the same source IP.  This wouldn't break anything, but it would limit the effectiveness of this check.

Also note that any IP-based filtering/security would require anyone who is using a reverse proxy to have it configured correctly so that source IPs are properly identified by WW.

Can cookies be used to store this information, and does that improve anything?  I realize cookies can be copied to another machine.

**Comment by drgrice1** [comment] 2023-11-09 17:47
Storing the information in an encrypted cookie is better.  It is not perfect, since cookies can be copied, but it is much harder to copy a cookie than the proctor username and key.  Particularly assuming that the proctor is paying some amount of attention.

**Comment by Alex-Jordan** [comment] 2024-08-11 03:16
Did #2334 address this?

**Comment by drgrice1** [comment] 2024-08-11 03:28
I think it mostly addresses this.  It is no longer possible to open a new version of a test with this approach.  However, it is still possible to copy the session and go elsewhere to continue to work on an in progress test before the time limit has expired.  Although it is more difficult because you have to copy the entire session (it would not be trivial to write that down, so a cut and paste is pretty much needed), and you must use a post request which is perhaps harder to engineer.

**Comment by somiaj** [comment] 2024-11-17 22:28
Although the problem isn't completely fixed (if someone is knowledgeable enough to copy a full session), should we still close this as fixed for now?

**Comment by drgrice1** [comment] 2024-11-17 22:32
I suppose for now. I don't think that better can be done with the current authentication system.  And I don't know of a better system at this point.

**Comment by somiaj** [comment] 2024-11-18 22:46
Closing this issue as fixed minus the session can be copied which is the best the current system allows.

**Closed by somiaj** 2024-11-18 22:46 UTC
