### ISSUE TITLE
Answers that exceed 127 characters can not be saved to the database

### ISSUE THREAD

**Issue by drgrice1** [openwebwork/webwork2#1031] opened 2019-10-02 22:50 UTC
This is discussed in http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4662#p13763.
This can happen with the latex form of a student answer saved in the sticky answers for MathQuill answer boxes.  This also happens for essay type answers.  This did not happen with lengthy answers with WeBWorK 2.14, and is perhaps related to the database switch to utf8mb4.

**Comment by mgage** [comment] 2019-10-03 00:25
Thanks very much Glenn.  We'll need to track this down.

**Comment by taniwallach** [comment] 2019-10-03 13:31
Based on the discussion in the forum - it seems that the underlying problem is that `Storable::nfreeze` adds a byte count as a "byte" and when that is over (2^7)-1 it often is not a valid UTF-8 value, so the database rejects the string. 

This is handled done in `lib/WeBWorK/Utils.pm` by `decodeAnswers()` and `decodeAnswers()`.

Instead of fixing this by changing the database field to a BLOB, I would like to propose that we look into using JSON to serialize the data for this database field, but try to do so in a backwards compatible way by having `decodeAnswers()` in `lib/WeBWorK/Utils.pm` decide whether to use the "old" (thaw) approach or the JSON approach based on some regexp check of the contents of the field. All new data put into this field would be serialized/deserialized using standard Perl JSON tools, and only old style `nfreeze` data would be deserialized using the old code.

What do people think of this idea?

**Comment by taniwallach** [comment] 2019-10-03 13:54
A related issue, which I have not have yet had a chance to investigate is that the current code to store data in the `last_answer` database field does not seem to properly handle any answers which use UTF-8 characters which are not in Latin-1. I tend to suspect that the problem is somehow related either to `Storable::nfreeze` not working well with real Unicode data, or an issue with the character count. In any case, I suspect that using JSON to store the serialized form is likely to work and overcome that issue also.

**Comment by drgrice1** [comment] 2019-10-03 14:12
> Instead of fixing this by changing the database field to a BLOB, I would like to propose that we look into using JSON to serialize the data for this database field, but try to do so in a backwards compatible way by having `decodeAnswers()` in `lib/WeBWorK/Utils.pm` decide whether to use the "old" (thaw) approach or the JSON approach based on some regexp check of the contents of the field. All new data put into this field would be serialized/deserialized using standard Perl JSON tools, and only old style `nfreeze` data would be deserialized using the old code.

That is feasible, but we will have to be careful to make sure there is a reliable way to distinguish between the two data forms.  Although the data types in the database of several fields have already been changed for the multibyte transition (VARCHAR lengths).  So my comment in the forum about upgrading the database properly still will need to be dealt with.  It has also occurred to me that disabling utf8 via the ENABLE_UTF8MB4 option in site.conf may not actually work quite right due to the change in those data types.  It certainly doesn't fix this issue.

> A related issue, which I have not have yet had a chance to investigate is that the current code to store data in the `last_answer` database field does not seem to properly handle any answers which use UTF-8 characters which are not in Latin-1. I tend to suspect that the problem is somehow related either to `Storable::nfreeze` not working well with real Unicode data, or an issue with the character count. In any case, I suspect that using JSON to store the serialized form is likely to work and overcome that issue also.

I don't think this is an entirely different issue.  Note that `Storable::nfreeze` does work well with real Unicode data according to the documentation since Perl 5.6.  I believe that is in fact the issue here.  `Storable::nfreeze` is encoding the UTF-8 characters in its way, after which they are no longer multibyte characters.  Then MySQL tries to deal with them as UTF-8 characters and that causes a problem.  Basically, at some point someone misinterpreted what `Storable::nfreeze` data is.  It is a binary form of data and always has been.  That should have never been a TEXT data field.  The change from utf8 to utf8mb4 is just highlighting this misinterpretation.

A switch to JSON should fix both of these issues.  Although I am certain switching to a BLOB data type also would.

**Comment by mgage** [comment] 2019-10-03 16:13
Transferring some of the discussion from the forum to issues so that it doesn’t get lost.

Glenn has reply to this that using BLOB or JSON would be better and I think he is probably right.

If   nfreeze produces binary data is there any downside to using BLOB as the data type for last_answer (and any other places where we freeze data).
Would that be the easiest change to make?  Is there any particular advantage to using JSON?


Mike

------------------------------------------------------------------------------------------------

Here is the result of my experiment to convert the serialized strings to base64 before storing.  It also appeared to work.


Preliminary report. I agree that changing encode and decode answers is the right approach. I just did a test in a fresh install of webwork 2.15 in docker and made these changes:

sub decodeAnswers($) {
 my $serialized = shift;
 return unless defined $serialized and $serialized;
 my $array_ref = eval{ Storable::thaw(decode_utf8_base64($serialized)) };

 if ($@ or !defined $array_ref) {
 # My hope is that this next warning is no longer needed since there are few legacy base64 days and the fix seems transparent.
 # warn "problem fetching answers -- possibly left over from base64 days. Not to worry -- press preview or submit and this will go away permanently for this question. $@";
 return ();
 } else {
 return @{$array_ref};
 }
}

and

sub encodeAnswers(\%\@) {
 my %hash = %{shift()};
 my @order = @{shift()};
 my @ordered_hash = ();
 foreach my $key (@order) {
 push @ordered_hash, $key, $hash{$key};
 }
 return encode_utf8_base64( Storable::nfreeze( \@ordered_hash)) ;

}

If I entered the string


0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

before the change I would get a database error. After the change

webwork simply reports correctly that my answer is incorrect. I haven't thought how to make this backwards compatible yet. It might be easier to implement than switching to JSON but there may be other reasons to switch to JSON. In any case it seems to confirm that the basic source of this bug is the freeze/thaw operation.


<http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4662#p13775>

**Comment by taniwallach** [comment] 2019-10-03 16:31
> It has also occurred to me that disabling utf8 via the ENABLE_UTF8MB4 option in site.conf may not actually work quite right due to the change in those data types. It certainly doesn't fix this issue.

`ENABLE_UTF8MB4` was only intended to swap from the full 4-byte UTF-8 (`utf8mb4`) and mySQL's 3-byte partial UTF-8 (`utf8`). The partial `utf8` also would reject any invalid byte sequences rejected by `utf8mb4` and also any 4-byte characters which cannot be stored due to the 3-byte restruction.

> Note that Storable::nfreeze does work well with real Unicode data according to the documentation since Perl 5.6. I believe that is in fact the issue here. Storable::nfreeze is encoding the UTF-8 characters in its way, after which they are no longer multibyte characters. Then MySQL tries to deal with them as UTF-8 characters and that causes a problem. Basically, at some point someone misinterpreted what Storable::nfreeze data is. It is a binary form of data and always has been. That should have never been a TEXT data field. The change from utf8 to utf8mb4 is just highlighting this misinterpretation.

Quite possibly it should always have been a BLOB: the length code shows up as Control-A for 1 byte, etc. but until now WeBWorK and mySQL managed to handle such things, apparently because formally just about any 8-bit character was apparently permitted in a TEXT field, and no one noticed (or at least apparently no one reported) any problem with the functionality for many years (or at least since WW stopped using base64 in the flow of the encode/decode).

One of my motivations is the proposed change to JSON is that it is a modern serialization format which is mostly human readable, and that there are existing libraries to serialize/deserialize which should not run into any problem with Unicode text, which should support any necessary "escaping" automatically, and which should be pretty easy to drop in the code with minimal effort.

> That is feasible, but we will have to be careful to make sure there is a reliable way to distinguish between the two data forms. 

I agree, but I do not expect it to be that hard to distinguish the 2 forms. I suspect that the first character of the JSON serialization will always be `{` are we are serializing a hash. On the other hand, the data from the current method never seems to start with a `{`.

I took a look inside my databases at the contents of the `last_answer` when it was not null.

The start of any non-null data always seems to have at least **four** control-characters, usually starting as `^E^M` where the `^E` is Control-M = `0x05`, but I'm not sure what put that into the serialized data.

Also every record I found contained:
```
^M
AnSwEr0001
```
where the `^M` is Control-M = `0x0d`. 

This is probably not really sufficient, as gateway quizes and questions with named answers may not have a field called `AnSwEr0001`

```
select count(*) from COURSEID_problem_user where not (last_answer is null ) and not ( last_answer regexp '\nAnSwEr0001' );
select count(*) from COURSEID_problem_user where not (last_answer is null ) and not ( last_answer regexp '^[[:cntrl:]][[:cntrl:]][[:cntrl:]][[:cntrl:]]' );
```
are all return no matches found.

It there is some consensus that this make sense, I will try to code something and make a PR for people to test.

**Comment by taniwallach** [comment] 2019-10-03 16:36
@drgrice1 - If you have a course where you set up the use of BLOB. can you test whether a Unicode character such as א can be included in an answer and be sent back as the prior answer?

@mgage - Adding the base64 encoding is likely to work, but turns that data in the database into gibberish, whereas now it is sufficiently human readable to be of some direct use for debugging purposes. JSON serialized data should also be reasonable human readable.

**Comment by drgrice1** [comment] 2019-10-03 16:36
I was thinking the same thing about the starting brace `{` versus the `^M`.  AnSwEr0001 should not be part of the distinction though.  That will be entirely unreliable.  Named answers, multianswers, and gateway quizzes will certainly break that.  I think it should be reliable just to check if the string starts with `{` or not.

**Comment by drgrice1** [comment] 2019-10-03 16:42
> @drgrice1 - If you have a course where you set up the use of BLOB. can you test whether a Unicode character such as א can be included in an answer and be sent back as the prior answer?

It looks like it doesn't work with BLOB.  So then JSON is probably the way to go.

**Comment by taniwallach** [comment] 2019-10-03 17:17
I'll have a PR ready soon... But the old code used and returned "ordered" arrays of key+value pairs, so that will be used and JSON detection will use `[` as the first character and `]` as the last character as the initial test.

**Comment by drgrice1** [comment] 2019-10-03 17:31
I just looked at the error that occurred when I tried to enter Aleph before.  It was not the last answer that failed, it was the past answer that failed.  The course that I tested it on does not have its database properly converted to utf8mb4.  So that test was not conclusive.  I will try another test once I get a course properly set up.  This just confirms what I have said about needing to fix upgrading the databases for courses.

I think that the JSON way to go may be better in any case.

**Comment by mgage** [comment] 2019-10-03 17:51
OK.  I agree we need to fix the upgrade process to do a better job of altering field values that have changed.
I agree that JSON is the way to go for storage of serialized data.

I have questions about which of these changes need to go into webwork-2.15 — I’m getting antsy to get that off the table, but ….
If we can make changes for storing via JSON pretty quickly then we’ll try to include that in webwork-2.15

Take care,

Mike



On Oct 3, 2019, at 1:31 PM, Glenn Rice <notifications@github.com<mailto:notifications@github.com>> wrote:


I just looked at the error that occurred when I tried to enter Aleph before. It was not the last answer that failed, it was the past answer that failed. The course that I tested it on does not have its database properly converted to utf8mb4. So that test was not conclusive. I will try another test once I get a course properly set up. This just confirms what I have said about needing to fix upgrading the databases for courses.

I think that the JSON way to go may be better in any case.

**Comment by taniwallach** [comment] 2019-10-03 17:56
>  have questions about which of these changes need to go into webwork-2.15 — I’m getting antsy to get that off the table, but …. If we can make changes for storing via JSON pretty quickly then we’ll try to include that in webwork-2.15 

I agree, but since this is a bug caused by the transition to UTF-8 support, if we don't fix it now, before the release of WW 2.15, we will probably need to fix it as a hot-fix. The PR is ready to test, and unless something terrible shows up, can probably be merged quite soon.

It would be good if someone tested the change with MathQuill enabled.

**Comment by mgage** [comment] 2019-10-03 18:20
I've done one test -- on a fresh webwork 2.15 installed in docker.  It worked fine -- it took long strings and it handled hebrew characters.  I'll test later on existing courses on other machines.

**Comment by drgrice1** [comment] 2019-10-03 18:43
Just a quick follow up since I tested this properly.  Entering aleph with BLOB did work in the end.  Once I set up a course that properly had utf8mb4 encoding enabled.

**Closed** 2019-10-04 05:08 UTC
