### ISSUE TITLE
safari and datepicker issue

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1873] opened 2023-01-30 17:28 UTC
In Safari, if you go to the Hmwk Sets Editor, Edit tab, and click to edit a set, there is a console error from  the datepicker:

```
RangeError: timeZoneName must be "short" or "long"
```

This is leading to the times in the input fields being filled in as epoch timestamps instead of human readable dates. I do not see this error in Fiirefox, Chrome, or Edge for Mac. This was reported by a Runestone hosting user.

**Comment by drgrice1** [comment] 2023-01-30 17:56
Does it also happen on the Hmwk Sets Editor page when not in edit mode?  Even if you click on the "Import" tab?
Does it also happen on the Set Detail page?
What about on the UserDetail page (the "Sets assigned to ...." page)?

It would be really odd if it only happens on the Hmwk Sets Editor page, and not the pages I asked about above.  They all use the same code, and `timeZoneName` is set to `shortOffset` in this code.  That is a valid value for `timeZoneName` according to the specifications.

Also, can you reproduce this on the develop branch?

**Comment by dlglin** [comment] 2023-01-30 18:06
I can't reproduce this.  I'm running Safari 16.3 (18614.4.6.1.5).
<img width="1723" alt="Screenshot 2023-01-30 at 11 03 48 AM" src="https://user-images.githubusercontent.com/1794586/215558413-802dd7af-7ee2-4d6c-9cf6-6142d0904fbc.png">

**Comment by Alex-Jordan** [comment] 2023-01-30 18:21
> Does it also happen on the Hmwk Sets Editor page when not in edit mode? Even if you click on the "Import" tab?

The console error happens. But you wouldn't notice, because nothing is odd about the dates you see. They are human readable.

>  Does it also happen on the Set Detail page?

Yes. Console error, and dates as timestamps.

>  What about on the UserDetail page (the "Sets assigned to ...." page)?

The console error is there. At first, no timestamps to see because the input fields are blank. If I put a date in the filed and try to save, there is an apache warning: `Argument "1/31/23, 11:59 PM" isn't numeric in numeric lt (<) at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetDetail.pm line 1203.` and an apache error `DBD::MariaDB::st execute failed: Data truncated for column 'open_date' at row 1 at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 881.`

> Also, can you reproduce this on the develop branch?

I don't have an up to date develop branch server up right now. My develop server is probably much closer to 2.17. I have a sense from loosely monitoring development that it will be nontrivial to update my develop server. Briefly, will it take much effort beyond git pulling?

**Comment by Alex-Jordan** [comment] 2023-01-30 18:27
> I can't reproduce this. I'm running Safari 16.3 (18614.4.6.1.5).

Well, that might be important here. I have Version 14.1.2 (14611.3.10.1.7). It's from OS Mojave, supported 2018–2021. (I can't upgrade this school-owned machine on my own.)

I am not sure what version the reporting instructor has, but I asked.

If this is resolved by having up to date Safari, I suppose we do nothing, but be mindful of older Safari having issues?

**Comment by drgrice1** [comment] 2023-01-30 22:29
Getting a development instance of webwork2 running on a local machine is much easier than it used to be with the develop branch.  If you are on OSX, then @pstaapb and @drdrew42 can help you much better than I.  If you have an Ubuntu machine that you can set up for development, I can help you with that.  You should read the webwork2/conf/README.md file.  I also started an installation manual for 2.18 on Ubuntu in the last few days.  It is at https://webwork.maa.org/wiki/Installation_Manual_for_2.18_on_Ubuntu.

**Comment by pstaabp** [comment] 2023-01-31 11:53
@Alex-Jordan I think running development is much easier now than before and I run everything natively on OSX--I would imagine everything would run fine on Mojave.

**Comment by drgrice1** [comment] 2023-04-29 14:27
Fixed by #1875.

**Closed by drgrice1** 2023-04-29 14:27 UTC
