### ISSUE TITLE
project -- translate strings originating in javaScript code

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#949] opened 2019-05-25 03:53 UTC
There appear to be a number of methods for translating javaScript code.  Some of them similar to the gettext (or maketext) procedure we implemented in the perl code.  (They seem to consider gettext() and old fashioned standard so perhaps we can do better with the javaScript strings.

**Comment by taniwallach** [comment] 2019-08-01 10:25
See what CCDMD has: https://github.com/openwebwork/webwork2/compare/WeBWorK-2.15...CCDMD:CCDMD_H2018#files_bucket
See https://github.com/openwebwork/webwork2/issues/914

**Comment by drgrice1** [comment] 2024-12-18 16:27
Closing this as a duplicate of #781.

**Closed by drgrice1** 2024-12-18 16:27 UTC
