### ISSUE TITLE
Workflow for new OPL-update

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1715] opened 2022-05-29 11:04 UTC
I merged in #1693 and thought that an early Sunday morning would be a good time to update our campus server and pull in the new WeBWorK-2.17 code.  After all the standard upgrades, I got to the LibraryBrowser and got the 
```
DBD::MariaDB::db selectall_arrayref failed: Unknown column 'pgf.libraryroot' in 'where clause' at 
```
error and knew that we needed a database upgrade.  I realized I should do an OPL-update, however that did not fix this problem.  I'm running `OPL-update-legacy` right now in case someone wants to use this soon.

This may just be my misunderstanding about what the new `OPL-update` does.  Either way, we need to document this.

**Comment by drgrice1** [comment] 2022-05-29 11:06
The issue is that we do not have a release for the pull request that you merged yet.  So for now, you will need to run `OPL-update-legacy`.

**Comment by drgrice1** [comment] 2022-05-29 11:10
So, we do not need documentation on this really.  We just need an OPL metadata release.  Then it will work as expected.   I assume that @drdrew42 will take care of this shortly.

**Comment by pstaabp** [comment] 2022-05-29 11:12
Right. When I tested I used drew's OPL release and I didn't change that in `download-OPL-metadata-release` on our server.

**Comment by taniwallach** [comment] 2022-07-11 09:53
There is already a release on the OPL.

**Closed by taniwallach** 2022-07-11 09:53 UTC
