### ISSUE TITLE
Problem installing XMLRPC::Lite from CPAN (in docker)

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork2#939] opened 2019-05-16 13:37 UTC
I have problems building the webwork docker image, which seem to be caused by the CPAN package [XMLRPC::Lite](https://metacpan.org/pod/XMLRPC::Lite). Its installation sometimes fails. This seems to occur randomly; at least I have not figured out the exact circumstances yet. The following bug reports confirm this:

https://rt.cpan.org/Public/Bug/Display.html?id=127761
https://rt.cpan.org/Public/Bug/Display.html?id=92742

There is also a related bug report in Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924391

It is fixed in Debian:

https://salsa.debian.org/perl-team/modules/packages/libxmlrpc-lite-perl/commit/62dc58b3d8e07c9ab79fa96cc4d8198df534febe

However it seems that it is not fixed in CPAN.

A workaround might be to install the package not from CPAN, but using apt-get.

This could have been the cause for #903.

**Comment by taniwallach** [comment] 2019-05-16 13:45
@mgage  and I have also discussed this - it seems that the install from CPAN runs some tests which can fail when the servers being used for the test do not respond quickly enough...

We also came to conclusion that using the Debian package to install this package should hopefully avoid the annoying problem which sometimes breaks the Docker builds.

However, I think that so far the changes to Dockerfile may either be in one one of the internationalization development branches, on some private branch, or maybe only on one of our machines.

Sorry that I have not had time to test this and make a PR for develop and/or master.

**Comment by heiderich** [comment] 2019-05-16 14:44
@taniwallach Thanks for the confirmation.

**Comment by mgage** [comment] 2019-05-16 14:54
I had some similar problems.  My fix is in the branch multilingual on github.com/mgage/webwork2<http://github.com/mgage/webwork2> and is pull request #934.

Unless there are objections I hope to merge this #934 into develop fairly soon so that we don’t have too many development branches lying around.

I’m pretty confident that multilingual will not interfere with existing installations that use latin-1.  It also works well with fresh installations
using utf8mb4.  There remains the question of what measures (if any) need to be taken to switch existing courses using extended character
sets over to using the new multilingual branch.  Florian and Tani and others using extended character sets do you have any comments on this?

Take care,
Mike

On May 16, 2019, at 9:37 AM, Florian Heiderich <notifications@github.com<mailto:notifications@github.com>> wrote:


I have problems building the webwork docker image, which seem to be caused by the CPAN package XMLRPC::Lite<https://urldefense.proofpoint.com/v2/url?u=https-3A__metacpan.org_pod_XMLRPC-3A-3ALite&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=J3DAG5sbr4b9Cbtk8_OqWY9XT4sdZAJhbm7r5FaZV40&e=>. Its installation sometimes fails. This seems to occur randomly; at least I have not figured out the exact circumstances yet. The following bug reports confirm this:

https://rt.cpan.org/Public/Bug/Display.html?id=127761<https://urldefense.proofpoint.com/v2/url?u=https-3A__rt.cpan.org_Public_Bug_Display.html-3Fid-3D127761&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=U_Zq93GlwziXqFayhFBaLH7Q6dQsiVDFi8LzEG0yFsM&e=>
https://rt.cpan.org/Public/Bug/Display.html?id=92742<https://urldefense.proofpoint.com/v2/url?u=https-3A__rt.cpan.org_Public_Bug_Display.html-3Fid-3D92742&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=GI2wglR89_TqrMQbs0Kcg4TI45wG_QnayczbJ_u8hPg&e=>

There is also a related bug report in Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924391<https://urldefense.proofpoint.com/v2/url?u=https-3A__bugs.debian.org_cgi-2Dbin_bugreport.cgi-3Fbug-3D924391&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=rNS4HjYSLAQBreISp6NFs8MxJq6o2NNf20bcPNLuj2I&e=>

It is fixed in Debian:

https://salsa.debian.org/perl-team/modules/packages/libxmlrpc-lite-perl/commit/62dc58b3d8e07c9ab79fa96cc4d8198df534febe<https://urldefense.proofpoint.com/v2/url?u=https-3A__salsa.debian.org_perl-2Dteam_modules_packages_libxmlrpc-2Dlite-2Dperl_commit_62dc58b3d8e07c9ab79fa96cc4d8198df534febe&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=ktxRvyjw_LXGrw2WG6K_1gQS4sVu7MEpgBVAdWgJqFE&e=>

However it seems that it is not fixed in CPAN.

A workaround might be to install the package not from CPAN, but using apt-get.

This could have been the cause for #903<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_openwebwork_webwork2_issues_903&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=h3LJb2sTYfSy7d8JoZaR6IiHQZzHSleCz8Y9aT26AHA&s=MYnfsJoGFVgCeR2ZOfDjY3Ut32nJ2IXFBPRRsq4QfZc&e=>.

**Comment by mgage** [comment] 2019-05-23 23:23
resolved by pull request #940

**Closed** 2019-05-23 23:23 UTC
