### ISSUE TITLE
Temporary files are accessible without a login

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1075] opened 2020-02-11 22:27 UTC
On Feb 10, 2020, at 3:53 PM, Glenn Rice <grice1@missouriwestern.edu> wrote:

Danny seems to hit on the real problem here.  The TTU server has directory browsing enabled.  By default apache2 does this, but for a secure server it should be disabled.  To disable directory browsing for apache2 edit /etc/apache2/apache2.conf and remove "Indexes" from the root directory settings.

The default settings look something like the following:

<Directory />
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

Perhaps this should be added to the installation documentation for webwork.  Of course this still doesn't solve the issue if someone the exact path to a file. 

Glenn

On 2/10/20 4:43 PM, Danny Glin wrote:
A couple of points:

It looks like there is a configuration issue with the TTU server which allows temporary directory contents to be viewed from the web.  For example if I visit https://webwork.math.ttu.edu/wwtmp/ I am able to navigate through any of the tmp directories.  When I try this on my server, I get a landing page telling me that I shouldn’t be there, and if I try to view a subdirectory I get a 403 Forbidden error.  This configuration difference is likely why google was able to index the tmp files on the TTU server.  Adding a robots.txt file as Mike suggests would be another layer of protection to try to prevent these files from showing up on google.  Even with these fixes, someone who knows the exact path to a hardcopy file would still be able to access it.  Having a cron job periodically delete these mitigates, but does not solve the issue.

I had the same initial reaction as Tani regarding temporary files containing PPI;  I took a quick look at the files served from the htdocs/tmp directory, and it looks like it is only image files and pdf hardcopies of homework sets.  I can’t think of a scenario where an image related to a webwork exercise would contain PPI.  If that is the case, then it is just the hardcopy pdfs that are at issue.  Tani’s solution is probably the appropriate one.  

Danny

On Feb 9, 2020, at 3:06 PM, Nathan Wallach <taniwallach@gmail.com> wrote:

1. "We" actually just leaked this persons name + email address + some of his personal situation (from the request) not only to the recipients of this list but via the public archive at:  http://webwork.maa.org/pipermail/webwork-devel/ . I edited the older mails below so this message does not repeat that. Can someone manually edit the email archive to clean up the prior postst?

2. I think that Arnie's idea may be a very good thing to consider  - as we want WeBWorK to be compliant with the best practices of protecting personal information, so files which are intended to include such information should not be created as publicly available files even if hidden away under some random looking paths, if at all possible.

Overall, AFAIK, most supporting material (images - standard or custom, CSS files, JavaScript files) served as static content (at least once generated) is not going to contain any PII (personally identifiable information), while most WeBWorK pages which do contain PII are dynamically generated for a logged in user. 

The obvious exception (not that someone pointed a finger at it) seems to be the "hardcopy" files.

At least one type of "specially generated files' - scoring files - seem to be available only to a logged in user. Ex: In order to download the CSV grading file I see a link like:

https://hostname.domain/webwork2/courseID/instructor/scoringDownload/?user=username&key=session_key&getFile=courseID_totals.csv&effectiveUser=username

and the CSV file itself is not under htdocs/tmp but instead under courses/courseID/scoring/ so does not seem to be something which can be severed without being authenticated and authorized by the WW code.

The processing seems to be handled by lib/WeBWorK/ContentGenerator/Instructor/ScoringDownload.pm which is activated by suitable code in lib/WeBWorK/URLPath.pm.

I suspect that a similar approach would provide a more secure means to distributing the PDF files, and the expense of needing to manage a new location for temporary files which should be periodically cleaned out and otherwise managed, and the expense of needing to have the WW code (and not  lighttpd) server them.

What do other people think?

Tani

On Sun, Feb 9, 2020 at 9:54 PM Arnold Pizer <apizer@math.rochester.edu> wrote:
Also maybe there is a more secure way to serve PDF files than we are doing.

Arnie

On Sat, Feb 8, 2020, 8:48 PM mgage <gage@math.rochester.edu> wrote:
This was on a TTU server.  And I expect you are right Arnie about the set up.  
Perhaps we should recommend a no-robots file as well.

Take care,

Mike

On Feb 8, 2020, at 10:19 PM, Arnold Pizer <apizer@math.rochester.edu> wrote:

Hi,

I assume when the new server was set up, cron jobs to remove temporary files were not set up.  See 
 "Using Cron Jobs to remove temporary files" in
http://webwork.maa.org/wiki/Clean_Out_Temporary_Files

Arnie

**Comment by dlglin** [comment] 2020-02-11 22:31
On my server I still have the default apache settings that Glenn included below, and yet my WW install does block directory listing.

Looking at lines 163-168 of webwork.apache2.4-config.dist:

push @Alias, [ $webwork_htdocs_url => $webwork_htdocs_dir ];
$Directory{$webwork_htdocs_dir} = {
        Require => "all granted",
	Options => "FollowSymLinks",
	AllowOverride => "none",
};

If I understand this correctly, the fact that the Options directive here does not contain “Indexes” should imply that Indexes are not enabled for this directory, unless there is something in the apache config which overrides this.

One difference is that the html/tmp URL on the TTU server is /wwtmp as opposed to /webwork2_files/tmp, which was probably set up according to the instructions at http://webwork.maa.org/wiki/Store_WeBWorK%27s_temporary_files_in_a_separate_directory_or_partition.  It’s possible that something in this change lead to Indexes being enabled.

There are a couple of things we could do within the WeBWorK code to try to mitigate this.  I haven't investigated how hard these would be, and am open to thoughts on whether they are even good ideas:

1. Create a robots.txt file to prevent search engines from indexing pages if they are visible.
2. Include a .htaccess file in the top tmp directory turning off Indexes
3. When a new subdirectory is created, automatically create a placeholder index.html file which says something like "you shouldn't be seeing this page".

**Comment by taniwallach** [comment] 2020-02-14 13:14
> If I understand this correctly, the fact that the Options directive here does not contain “Indexes” should imply that Indexes are not enabled for this directory, unless there is something in the apache config which overrides this.
> 
> One difference is that the html/tmp URL on the TTU server is /wwtmp as opposed to /webwork2_files/tmp, which was probably set up according to the instructions at http://webwork.maa.org/wiki/Store_WeBWorK%27s_temporary_files_in_a_separate_directory_or_partition. It’s possible that something in this change lead to Indexes being enabled.

My (Docker based) servers also are not allowing access to `/webwork2_files/tmp/` ex: `http://webwork.technion.ac.il/webwork2_files/tmp/` so the default config is certainly preventing access to indices. Thus, Danny's conclusion that the problem is that this is not happening for the relocated temp file location seems quite logical.
 
> 1. Create a robots.txt file to prevent search engines from indexing pages if they are visible.

Only helps partially, as only "honest" search engines will respect it.

> 2. Include a .htaccess file in the top tmp directory turning off Indexes

If I recall, even Apache does not always respect such files, depending on how it is configured.
Not sure if this would work with lighttpd, or other options for serving static content not via Apache.
Would depend on the system managers doing it, and doing it properly.

> 3. When a new subdirectory is created, automatically create a placeholder index.html file which says something like "you shouldn't be seeing this page".

This would certainly help, and as all hardcopy files are in a single subdirectory per course, it should not be hard to do. I think for a first stage fix - it is probably worth the effort.

However, the path to the PDF files are pretty predictable:
`/webwork2_files/tmp/courseID/hardcopy/courseID.userID.setID.pdf` so any student can easily guess the URL of fellow students files. A potential hacker who has prior access to a list of student email addresses and sees the courseID from a main landing page can also guess URLS if simple assignment names are used (like HW1, etc.).

I still think the long term solution would be to serve hardcopy files directly from the WW code to authenticated users without placing them at a web available location.

**Comment by taniwallach** [comment] 2021-07-28 21:29
@drgrice1 @mgage @pstaabp @dlglin 
During the meeting today this issue was raised as one of the more pressing things to work on for a 2.17 release.
We would like to make sure that files with "personal information" such as that which will be in hardcopy files is not open to whoever has the URL.
In terms of generated problem resources (ex. images), it seems that the best approach would be to prevent PG from having access to PII in general (and to handle what is needed for "header" generation in a different or reasonably secure manner). See: https://github.com/openwebwork/webwork3/discussions/18

**Comment by drgrice1** [comment] 2022-04-01 22:27
This issue is fixed by #1621.

**Closed by drgrice1** 2022-04-01 22:27 UTC
Labels: Requires Attention
