### ISSUE TITLE
WW+Canvas - LTI - issue with spam (frequent email notification) generated by grade passback of old unchanged grades

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1028] opened 2019-09-29 06:58 UTC
Summary from Tim Payer's forum post:

> Currently a few, but not all students are getting 30-40 Canvas email notifications for updated HW scores that have not been caused by the student. That is the student has completed the webwork assignment days or weeks ago but the LTI connection is prompting the student that their score has been updated when no such change has taken place.

I tried to merge Brian Walton's proposed changes (from the thread on bugs.webwork.maa.org) into the current version of `lib/WeBWorK/Authen/LTIAdvanced` but conditioned the new `warn` call he added after the readResult request from the lti_outcome_server_URL on `$ce->{debug_lti_grade_passback}`.

Code:
  - [SubmitGrade.pm.txt](https://github.com/openwebwork/webwork2/files/3666427/SubmitGrade.pm.txt) the patched version of the WW 2.15 file
  - [SubmitGrade.pm.2017-10-03-BrianWalton.txt](https://github.com/openwebwork/webwork2/files/3666428/SubmitGrade.pm.2017-10-03-BrianWalton.txt) Brian's original file from 2017.

See: 
  - http://bugs.webwork.maa.org/show_bug.cgi?id=3963
  - http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4661

---

See also a second issue with LTI grade passback reported at  http://bugs.webwork.maa.org/show_bug.cgi?id=3954 (which I did not examine).

**Comment by taniwallach** [comment] 2019-10-04 09:10
I tested the modified code on a server of mine, and LTI grade-passback works.
On that server, I commented out the `warn` in line 320 after the initial tests, and am giving Tim Payer access to an LTI course on the server for additional testing.

**Comment by taniwallach** [comment] 2021-01-19 14:10
Being addressed by an improved version in https://github.com/openwebwork/webwork2/pull/1177.

**Comment by drgrice1** [comment] 2021-01-19 14:22
I think that this issue should not be closed until the pull request addressing the issue is merged.

**Comment by taniwallach** [comment] 2021-01-19 14:40
OK. The PR references the issue, which is one of the motivations for the changes in https://github.com/openwebwork/webwork2/pull/1177.

I did not think we need to items tacking it.

**Comment by drgrice1** [comment] 2024-11-23 01:01
This has been fixed (and that fix improved upon).  In fact an upcoming pull request will greatly mitigate this issue.

**Closed by drgrice1** 2024-11-23 01:01 UTC
